export const HOTKEY_SCOPES = {
  GLOBAL: '*',
  ROOT: '.',
  SESSIONS: 'sessions',
  SESSIONS_ARCHIVED: 'sessions.archived',
  SESSIONS_BYPASS_PERMISSIONS_MODAL: 'sessions.bypassPermissionsModal',
  SESSION_DETAIL: 'sessions.details',
  SESSION_DETAIL_ARCHIVED: 'sessions.details.archived',
  DRAFT_LAUNCHER: 'sessions.details.draftLauncher',
  SESSION_DETAIL_FORK_IN_PROGRESS: 'sessions.details.forkInProgress',
  FORK_MODAL: 'sessions.details.forkModal',
  TOOL_RESULT_MODAL: 'sessions.details.toolResultModal',
  BYPASS_PERMISSIONS_MODAL: 'sessions.details.bypassPermissionsModal',
  SELECT_MODEL_MODAL: 'sessions.details.selectModelModal',
  DISCARD_DRAFT_DIALOG: 'sessions.details.discardDraftDialog',
  CREATE_DIRECTORY_DIALOG: 'sessions.details.createDirectoryDialog',
  THEME_SELECTOR: 'themeSelector',
  KEYBOARD_HELPER: 'keyboardHelper',
  SETTINGS_MODAL: 'settingsModal',
  TITLE_EDITING: 'sessions.details.titleEditing',
  ADDITIONAL_DIRECTORIES: 'additionalDirectories',
  SESSION_LAUNCHER: 'sessions.launcher',
  TELEMETRY_MODAL: 'telemetry-modal',
  CREATE_FOLDER_DIALOG: 'createFolderDialog',
  MOVE_TO_FOLDER_DIALOG: 'moveToFolderDialog',
  RENAME_FOLDER_DIALOG: 'renameFolderDialog',
  MOVE_FOLDER_DIALOG: 'moveFolderDialog',
  DELETE_FOLDER_DIALOG: 'deleteFolderDialog',
} as const

export type HotkeyScope = (typeof HOTKEY_SCOPES)[keyof typeof HOTKEY_SCOPES]
